<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2021-07-26T15:28:59" tests="0" file="cypress/integration/cucumber-tests/3SBanking.feature" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="3S Banking" timestamp="2021-07-26T15:28:59" tests="1" time="0.0000" failures="1">
    <testcase name="3S Banking Verify all 3S banking functionalities" time="0.0000" classname="Verify all 3S banking functionalities">
      <failure message="`cy.visit()` failed trying to load:

http://10.234.135.46:8022/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ETIMEDOUT 10.234.135.46:8022

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://10.234.135.46:8022/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ETIMEDOUT 10.234.135.46:8022

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
    at http://localhost:55646/__cypress/runner/cypress_runner.js:140471:23
    at visitFailedByErr (http://localhost:55646/__cypress/runner/cypress_runner.js:139830:12)
    at http://localhost:55646/__cypress/runner/cypress_runner.js:140470:11
    at tryCatcher (http://localhost:55646/__cypress/runner/cypress_runner.js:10798:23)
    at Promise._settlePromiseFromHandler (http://localhost:55646/__cypress/runner/cypress_runner.js:8733:31)
    at Promise._settlePromise (http://localhost:55646/__cypress/runner/cypress_runner.js:8790:18)
    at Promise._settlePromise0 (http://localhost:55646/__cypress/runner/cypress_runner.js:8835:10)
    at Promise._settlePromises (http://localhost:55646/__cypress/runner/cypress_runner.js:8911:18)
    at _drainQueueStep (http://localhost:55646/__cypress/runner/cypress_runner.js:5505:12)
    at _drainQueue (http://localhost:55646/__cypress/runner/cypress_runner.js:5498:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:55646/__cypress/runner/cypress_runner.js:5514:5)
    at Async.drainQueues (http://localhost:55646/__cypress/runner/cypress_runner.js:5384:14)
From Your Spec Code:
    at Function.visit (http://localhost:55646/__cypress/tests?p=cypress\integration\cucumber-tests\3SBanking.feature:200:10)
    at Context.eval (http://localhost:55646/__cypress/tests?p=cypress\integration\cucumber-tests\3SBanking.feature:47:25)
    at Context.resolveAndRunStepDefinition (http://localhost:55646/__cypress/tests?p=cypress\integration\cucumber-tests\3SBanking.feature:10660:9)
    at Context.eval (http://localhost:55646/__cypress/tests?p=cypress\integration\cucumber-tests\3SBanking.feature:9999:35)

From Node.js Internals:
  Error: connect ETIMEDOUT 10.234.135.46:8022
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
  ]]></failure>
    </testcase>
  </testsuite>
</testsuites>